# -*- coding: utf-8 -*-
"""Spence.Desjuan-PythonCode-ITT103-F2023.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PQ72_0KuQ09ean6L2k3_9gWMlPjEhQUw
"""



class BusReservation:
    def __init__(self, rows, columns):
        self.rows = rows
        self.columns = columns
        self.seats = [['O' for _ in range(columns)] for _ in range(rows)]
        self.reserved_seats = {'F': 0, 'B': 0, 'E': 0}

    def display_menu(self):
        print("UCC Signature Express Limited")
        print("<Welcome To Ucc Express!>")
        print("Reservation Options:")
        print("  First Class (F/f)")
        print("  Business Class (B/b)")
        print("  Economy Class (E/e)")
        print("  Quit or Cancel (Q/q)")

    def display_seats(self):
        for row in self.seats:
            print(" ".join(row))
        print()

    def reserve_seat(self, seat_class):
        print(f"Reserving seat for {seat_class} class.")
        row = int(input("Enter row number: "))
        column = int(input("Enter column number: "))

        if row <= 0:
            print("Number must be positive or greater than zero!")
            return

        if self.seats[row - 1][column - 1] == 'O':
            self.seats[row - 1][column - 1] = 'X'
            self.reserved_seats[seat_class.upper()] += 1
            print(f"Reserving seat: row {row} column {column:02}")
        else:
            print("Seat already reserved. Please choose another seat.")

    def run(self):
        while True:
            self.display_menu()
            choice = input("Please select an option: ")

            if choice.lower() == 'q':
                print(f"Reservation Type: First Class - {self.reserved_seats['F']}, "
                      f"Business Class - {self.reserved_seats['B']}, Economy Class - {self.reserved_seats['E']}")
                print(f"Total number of seats: {self.rows * self.columns}")
                print(f"Total number of seats reserved: {sum(self.reserved_seats.values())}")
                break
            elif choice.lower() in {'f', 'b', 'e'}:
                seat_class = 'First' if choice.lower() == 'f' else 'Business' if choice.lower() == 'b' else 'Economy'
                self.reserve_seat(choice.upper())
            else:
                print("Invalid choice!")

            if all(seat == 'X' for row in self.seats for seat in row):
                print("No more available seats!")
                break


if __name__ == "__main__":
    rows = 10  # You can set the number of rows and columns as needed
    columns = 4
    bus_reservation = BusReservation(rows, columns)
    bus_reservation.run()